//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJobsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid log_id { get; set; }
        public string log_detail { get; set; }
        public System.DateTime datetime { get; set; }
        public System.Guid work_id { get; set; }
        public System.Guid member_id { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Work Work { get; set; }
    }
}
