//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJobsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.Getjob = new HashSet<Getjob>();
        }
    
        public System.Guid work_id { get; set; }
        public string work_name { get; set; }
        public string work_desc { get; set; }
        public string tel { get; set; }
        public int labor_cost { get; set; }
        public System.DateTime duration { get; set; }
        public System.DateTime datetime { get; set; }
        public System.Guid member_id { get; set; }
        public System.Guid location_id { get; set; }
        public System.Guid status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Getjob> Getjob { get; set; }
        public virtual Location Location { get; set; }
        public virtual Member Member { get; set; }
        public virtual Status Status { get; set; }
    }
}
